### ISSUE TITLE
[https-dns-proxy] missing force_dns documentation

### ISSUE THREAD

**Issue by dgcampea** [stangri/docs.openwrt.melmac.ca#2]
Hi,

I can't find any documentation under <https://docs.openwrt.melmac.net/https-dns-proxy/> for options:
```
https-dns-proxy.config.force_dns
https-dns-proxy.config.force_dns_port
```
These were present after configuring a fresh install of _luci-app-https-dns-proxy_.

**Comment by stangri** [comment]
Thank you, resolved in https://github.com/stangri/docs.openwrt.melmac.net/commit/25db01806bec4b7b8ef685a4dcd25ceccd94e4d3.

Feel free to reopen if something is unclear or provided documentation is inadequte.

**Comment by dgcampea** [comment]
Thanks!
