### ISSUE TITLE
Dependencies dnsmasq-full

### ISSUE THREAD

**Issue by jirijanata** [stangri/docs.openwrt.melmac.ca#4]
I just tried to install dnsmasq-full from your guide, but some depencecies are missing so the installation wasn't succesfull (R7800, OpenWrt 21.02). With added dependencies worked the installation fine. So I would suggest to edit this part:

https://docs.openwrt.melmac.net/vpn-policy-routing/#how-to-install-dnsmasq-full

`opkg update; cd /tmp/ && opkg download dnsmasq-full; opkg install ipset libnettle8 libnetfilter-conntrack3;`

Thanks

**Comment by stangri** [comment]
This doesn't seem to have a line to install dnsmasq-full.

**Comment by jirijanata** [comment]
The second line is the same.

**Comment by stangri** [comment]
The `libnettle8` and `libnetfilter-conntrack3` are the dependencies of `dnsmasq-full`, so afaik they should be installed automatically with the installation of `dnsmasq-full`. 

I don't have a device to test, can you post the exact errors you've received when following instructions in the README?

**Comment by jirijanata** [comment]
But it will not install automatically - because the DNS resolution doesn’t work after dnsmasq deinstallation.

**Comment by stangri** [comment]
Ah, you're absolutely right, thank you!
