### ISSUE TITLE
PBR custom file

### ISSUE THREAD

**Issue by anomalyQC** [stangri/docs.openwrt.melmac.ca#7]
Hi!

Is it possible to add a list of your domains to a custom file using dnsmasq.nftset? Examples aws/netflix only for ip.
I want my list from a file, so as not to manually add many domains in one line, like here
option dest_addr 'youtube.com...........'

Is it possible?

OpenWrt 23.05.0-rc4

**Comment by stangri** [comment]
Yes, possible, check the README.
